version: 2
jobs:
  build-deploy-dev:
    docker:
      - image: max0ne/circleci-node-aws:latest
    steps:
      - checkout
      - run: npm i
      - run: npm run build-dev
      - run: 
          name: Deploy to S3
          command: aws s3 cp build s3://findmyclub-dev-frontend/ --recursive

  build-deploy-prod:
    docker:
      - image: max0ne/circleci-node-aws:latest
    steps:
      - checkout
      - run: npm i
      - run: npm run build-s3
      - run:
          name: Deploy to S3
          command: aws s3 cp build s3://findmyclub-prod-frontend/ --recursive

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-deploy-dev:
          filters:
            branches:
              only: dev
      - build-deploy-prod:
          filters:
            branches:
              only: master

